sonar.projectKey=web-expenses
sonar.projectName=Proyecto Angular
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_c2e201cb4da4ec9d85f43d01a2621bf4f77c12cb
